# This configuration file will be used to track CVEs that we can ignore for the
# latest release of Dangerzone, and offer our analysis.

ignore:
  # CVE-2024-11053
  # ==============
  #
  # NVD Entry: https://nvd.nist.gov/vuln/detail/CVE-2024-11053
  # Verdict: Dangerzone is not affected because libcurl is an HTTP client, and
  # the Dangerzone container does not make any network calls.
  - vulnerability: CVE-2024-11053
