# This configuration file will be used to track CVEs that we can ignore for the
# latest release of Dangerzone, and offer our analysis.

ignore:
  # CVE-2023-45853
  # ==============
  #
  # Debian tracker: https://security-tracker.debian.org/tracker/CVE-2023-45853
  # Verdict: Dangerzone is not affected because the zlib library in Debian is
  # built in a way that is not vulnerable.
  - vulnerability: CVE-2023-45853
  # CVE-2024-38428
  # ==============
  #
  # Debian tracker: https://security-tracker.debian.org/tracker/CVE-2024-38428
  # Verdict: Dangerzone is not affected because it doesn't use wget in the
  # container image (which also has no network connectivity).
  - vulnerability: CVE-2024-38428
  # CVE-2024-57823
  # ==============
  #
  # Debian tracker: https://security-tracker.debian.org/tracker/CVE-2024-57823
  # Verdict: Dangerzone is not affected. First things first, LibreOffice is
  # using this library for parsing RDF metadata in a document [1], and has
  # issued a fix for the vendored raptor2 package they have for other distros
  # [2].
  #
  # On the other hand, the Debian security team has stated that this is a minor
  # issue [3], and there's no fix from the developers yet. It seems that the
  # Debian package is not affected somehow by this CVE, probably due to the way
  # it's packaged.
  #
  # [1] https://wiki.documentfoundation.org/Documentation/DevGuide/Office_Development#RDF_metadata
  # [2] https://cgit.freedesktop.org/libreoffice/core/commit/?id=2b50dc0e4482ac0ad27d69147b4175e05af4fba4
  # [2] From https://security-tracker.debian.org/tracker/CVE-2024-57823:
  #
  #       [bookworm] - raptor2 <postponed> (Minor issue, revisit when fixed upstream)
  #
  - vulnerability: CVE-2024-57823
  # CVE-2025-0665
  # ==============
  #
  # Debian tracker: https://security-tracker.debian.org/tracker/CVE-2025-0665
  # Verdict: Dangerzone is not affected because the vulnerable code is not
  # present in Debian Bookworm. Also, libcurl is an HTTP client, and the
  # Dangerzone container does not make any network calls.
  - vulnerability: CVE-2025-0665
  # CVE-2025-43859
  # ==============
  #
  # GitHub advisory: https://github.com/advisories/GHSA-vqfr-h8mv-ghfj
  # Verdict: Dangerzone is not affected because the vulnerable code is triggered
  # when parsing HTTP requests, e.g., by web **servers**. Dangerzone on the
  # other hand performs HTTP requests, i.e., it operates as **client**.
  - vulnerability: CVE-2025-43859
  - vulnerability: GHSA-vqfr-h8mv-ghfj
  # CVE-2025-2866
  # ==============
  #
  # Debian tracker: https://security-tracker.debian.org/tracker/CVE-2025-2866
  # Verdict: Dangerzone is not affected because it does not rely on the
  # signature checking feature of LibreOffice.
  - vulnerability: CVE-2025-2866
  # CVE-2025-4802
  # ==============
  #
  # Debian tracker: https://security-tracker.debian.org/tracker/CVE-2025-4802
  # Verdict: Dangerzone is not affected for three reasons:
  # 1. We don't ship custom setuid programs, only the ones that get installed
  #    through the official repos. This is important because as the glibc
  #    advisory mentions:
  #
  #      The only viable vector for exploitation of this bug is local, if a
  #      static setuid program exists, and that program calls dlopen, then it
  #      may search LD_LIBRARY_PATH to locate the SONAME to load. No such
  #      program has been discovered at the time of publishing this advisory,
  #      but the presence of custom setuid programs, although strongly
  #      discouraged as a security practice, cannot be discounted.
  #
  # 2. We do not allow programs to elevate their privileges, either on the
  #    gVisor sandbox or the outer container, via the `no-new-privileges` flag.
  # 3. A quick search with `find / -perm 6000` in our container image yields no
  #    setuid programs. That's most likely due to the way we package our
  #    Dangerzone image, where we copy-paste binaries from the outer container
  #    to the inner one, destroying the setuid bits in the process.
  #
  # [1] https://sourceware.org/cgit/glibc/tree/advisories/GLIBC-SA-2025-0002
  - vulnerability: CVE-2025-4802
  # CVE-2025-4517
  # =============
  #
  # Debian tracker: https://security-tracker.debian.org/tracker/CVE-2025-4517
  # Verdict: Dangerzone is not affected for two reasons:
  # 1. We don't use `filter="data"` in our code.
  # 2. Our container image is based on Debian Bookworm, which is not affected by
  #    this bug.
  - vulnerability: CVE-2025-4517
